### ISSUE TITLE
[FEA] Implement a Series value_counts function, equivalent to pandas/cudf

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cudf#120]
## Request
As a user, I want to get the counts of each unique value in a given Series for potential distributional analyses and visualizations.

## Standard Dask Example

```
import cudf
import numpy as np
import pandas as pd
import dask_cudf
import dask.dataframe as dd

df = pd.DataFrame(
	{'a': list(range(20)),
	'b': list(reversed(range(20))),
	'c': list(range(20))})

ddf = dd.from_pandas(df, npartitions=2)

ddf.a.value_counts().compute()
19    1
18    1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
0     1
Name: a, dtype: int64
```

**Comment by mrocklin** [comment]
What happens when you try this with a dask dataframe with cudf dataframes?
Can I ask you to include a tracebackof the error?  This can help to
accelerate triage considerably.

**Comment by beckernick** [comment]
Yep, will add tonight. Working on the train caused me to forget including the failure mode for this issue 😄

**Comment by beckernick** [comment]
Problem was on my end. This pass through works as expected. Closing this issue.

**Comment by mrocklin** [comment]
Huzzah!
