### ISSUE TITLE
dask-dataframe is creating single task and npartition=1 always

### ISSUE THREAD

**Issue by AK-ayush** [rapidsai/dask-cudf#141]
I am going through this [blog](https://blog.dask.org/2019/01/29/cudf-joins). I have create cluster using dask-cuda with 2 V100 GPUs. And when I create a dask-dataframe, it is always created with single task and npartition=1 
but ideally it should create **4 task** and **npartitions=4**. 

`dask==1.1.3` 
`dask-cuda= build from master `
`dask-cudf= build from master `

![image](https://user-images.githubusercontent.com/11587734/54008387-7d9a4580-418c-11e9-963e-72e6c5d4d270.png)

---

`cudf is coming from 0.5 rapids container`
Even with these 1 task dataframes, when I perform join on these, It is giving error: `TypeError: merge() got an unexpected keyword argument 'suffixes' ` 
![image](https://user-images.githubusercontent.com/11587734/54008607-5001cc00-418d-11e9-9f0f-52d7a947f23d.png)

**Comment by kkraus14** [comment]
@AK-ayush I believe dask-cudf depends on cudf 0.6 which is not quite yet released. I know we added the suffixes keyword to cudf 0.6 in the past week or so.

**Comment by AK-ayush** [comment]
So `merge()` error can be solved by building cudf from source. 
But what the reason behind the `npartition=1` in dask dataframe in first sceenshot?

**Comment by mrocklin** [comment]
You can control the chunking with the chunks= keyword to the dask array functions.  http://docs.dask.org/en/latest/array-creation.html

**Comment by AK-ayush** [comment]
@mrocklin I can see in your blog that dask dataframe got partitioned in 64(8x8) partitions automatically but in my case it is just one partition every time, so I was just curious. 
Thanks for `chunks=` keyword though .

**Comment by mrocklin** [comment]
> that dask dataframe got partitioned in 64(8x8) partitions automatically

Hrm, that's definitely not standard behavior. Which blog?

**Comment by AK-ayush** [comment]
check out this github gist  https://gist.github.com/mrocklin/6e2c33c33b32bc324e3965212f202f66

**Comment by mrocklin** [comment]
If you don't specify chunks then it uses the default chunk size, which I
think is something like 128 MiB

**Comment by AK-ayush** [comment]
ohh okay, that sounds reasonable.   Thanks.

Both of my issue got answered, I guess, you can close this issue if you want.

**Comment by mrocklin** [comment]
Go for it.  You should be able to self-close by pressing the close button
just underneath this comment.

**Comment by mrocklin** [comment]
Thanks!

I spend my mornings handling around 50 of these sorts of issues across
different projects, so little things like self-closing are really
appreciated :)
