### ISSUE TITLE
Can't disable "UserWarning: Warning gzip compression does not support breaking apart files" warning

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#186]
When reading gzipped files with dask_cudf.read_csv, setting chunksize=None as directed still results in the warning:
```
/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0.0.0.dev0-py3.7.egg/dask_cudf/io/csv.py:44: UserWarning: Warning gzip compression does not support breaking apart files
Please ensure that each individual file can fit in memory and
use the keyword ``chunksize=None to remove this message``
Setting ``chunksize=(size of file)``
  "Setting ``chunksize=(size of file)``" % compression
```

**Comment by mrocklin** [comment]
Thanks for the bug report.  cc @quasiben

Short term you can always prepend your filename with `file://` to defer to
Dask DataFrame's implementation, which probably has this fixed, but routes
data through host memory

**Comment by quasiben** [comment]
Sorry, I dropped this.  Looks like @mrocklin's PR resolves the issue nicely
