### ISSUE TITLE
Incorrect string to string join results when reading multiple CSV files in either df

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#187]
Repro:
```
import pandas as pd
import dask_cudf

df = pd.DataFrame({'id': ['a', 'b', 'c']})
df.to_csv('a1.csv', index=False)
df.to_csv('a2.csv', index=False)

df = pd.DataFrame({'id': ['c', 'd', 'e']})
df.to_csv('b1.csv', index=False)
df.to_csv('b2.csv', index=False)

ddf_a = dask_cudf.read_csv('a*.csv')
ddf_b = dask_cudf.read_csv('b*.csv')

ddf_a.merge(ddf_b, on=['id'], how='inner').compute().to_pandas()
```
Result (an empty dataframe):
```
  | id
-- | --
```
Expected Result:
```
	id
0	c
1	c
2	c
3	c
```

Additional Notes:
This does _not_ happen when reading a single CSV at a time:
```
ddf_a = dask_cudf.read_csv('a1.csv')
ddf_b = dask_cudf.read_csv('b1.csv')
```

It does _not_ happen when the join column is numeric.

Using cuDF directly computes the join correctly:
```
import cudf

df_a = cudf.read_csv('a1.csv')
df_b = cudf.read_csv('b1.csv')

df_a.merge(df_b, on=['id'], how='inner').to_pandas()
```
```
    id
0    c
```

**Comment by VibhuJawa** [comment]
Please note that the merge fails when we merge dataframes with multiple partitions on a string.

It works fine on a single partition and also if we explicitly call dasks merge. 

# Code to reproduce bug:
```python
import dask_cudf
import cudf
import dask
import pandas as pd


df_1 = pd.DataFrame({'id': ['a', 'b', 'c']})
df_2 = pd.DataFrame({'id': ['c', 'd', 'e']})

ddf_1 = dask_cudf.from_cudf(cudf.from_pandas(df_1),npartitions=1)
ddf_2 = dask_cudf.from_cudf(cudf.from_pandas(df_2),npartitions=3)

print("\Explicit Dask Merge\n")
print(dask.dataframe.merge(ddf_1,ddf_2,on=['id'],how='inner').compute().to_pandas())

print("\nDask CUDF Inernal Merge\n")
print(ddf_1.merge(ddf_2, on =['id'],how='inner').compute().to_pandas())
```
### Output 
```
\Explicit Dask Merge

  id
0  c

Dask CUDF Inernal Merge

Empty DataFrame
Columns: [id]
Index: []
```

**Comment by mrocklin** [comment]
Right, so dask dataframe's implementation is fine here, but would only work when you have a single partition.

It's curious that this works on non-string types but doesn't work on string types.  (any thoughts on why this might be @kkraus14 ?)

@randerzander I think that the expected result should look more like the following for the `a*.csv` / `b*.csv` case.  Do you agree?

```
  id
0  c
1  c
2  c
3  c
```

**Comment by randerzander** [comment]
Yes, you're right. I copied/pasted the wrong expected output. That's what I get for filing issues late at night.

Fixed in the description as well. Thanks!

**Comment by quasiben** [comment]
I just tried this and got the correct output:

```python
In [55]: print("\Explicit Dask Merge\n")
    ...: print(dask.dataframe.merge(ddf_1,ddf_2,on=['id'],how='inner').compute().to_pandas())
    ...:
    ...: print("\nDask CUDF Inernal Merge\n")
    ...: print(ddf_1.merge(ddf_2, on =['id'],how='inner').compute().to_pandas())
\Explicit Dask Merge

  id
0  c

Dask CUDF Inernal Merge

  id
0  c
````

@randerzander can you try again ?

**Comment by quasiben** [comment]
I tried again today with most recent cudf/dask-cudf (branch-0.8) and I believe this is now fixed
