### ISSUE TITLE
dask_cudf version is displayed as 0.0.0.dev0

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/dask-cudf#190]
Hi,

I have just installed dask_cudf using conda on RAPIDS container 0.6.

When I run conda list, the version of the dask_cudf is displayed as follows:

> dask-cudf                 0.0.0.dev0               pypi_0    pypi

I think it should be 0.6.0.

Hope it helps.

**Comment by mrocklin** [comment]
@raydouglass

**Comment by miguelangel** [comment]
I have just downloaded the latest container (RAPIDS v0.7). It is working now.

Thank you!

![image](https://user-images.githubusercontent.com/26169771/57623891-08cef780-7591-11e9-8ed6-31d432ebc142.png)

**Comment by mrocklin** [comment]
Thanks for checking and closing!
