### ISSUE TITLE
In the entire pipeline of RAPIDS, how does RAPIDS keep the data in GPU memory? 

### ISSUE THREAD

**Issue by FullStackHan** [rapidsai/dask-cudf#203]
In the entire pipeline of RAPIDS, how does RAPIDS keep the data in GPU memory? For example, both the A process and the B process perform cuDF and cuML processing, and the output of the A process is handed to the B process for processing. As shown below, apche Arrow is in the entire pipeline phase of RAPIDS, so the data needs to be stored in the GUP memory all the time. But after the end of the A process, A's data should theoretically be released, how to pass it to the B program?
I saw this description on the HONE page of RAPIDS:

"Deep Learning Libraries"
"RAPIDS provides native array_interface support. This means data stored in Apache Arrow can be seamlessly pushed to deep learning frameworks that accept array_interface such as PyTorch and Chainer."

Therefore, I have two questions:

How does RAPIDS store data in GPU memory at all stages of the entire pipeline (cuDF, cuML, cuGraph, Deep Learning)?
How does the data stored in the GUP (Arow data) be pushed to the B process?

![2019-04-04_11-37-51](https://user-images.githubusercontent.com/13718710/55531388-ae629180-56dc-11e9-9395-adf89ca9920a.png)

**Comment by mrocklin** [comment]
> How does RAPIDS store data in GPU memory at all stages of the entire pipeline (cuDF, cuML, cuGraph, Deep Learning)?

This depends on the library you're using at the time.  For questions about a specific library I recommend referring to their documentation.  

> How does the data stored in the GUP (Arow data) be pushed to the B process?

You may want to look at Dask's distributed scheduler documentation, which has information about communication.  https://distributed.dask.org/en/latest/ .  You may also want to look at OpenUCX.
