### ISSUE TITLE
[FEA] Support transpose on dataframes.

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cudf#208]
### Description
As a user, I'd like to be able to transpose my dask_cudf dataframes. I can currently do this in cudf, but not in dask_cudf.

### Desired Behavior
The equivalent of the following with dask_cudf dataframes:

```
import cudf
sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6]})
print(sample)
print(sample.transpose())
   a  b
0  1  4
1  2  5
2  3  6
   0  1  2
0  1  2  3
1  4  5  6
```

### Additional Context
This should probably be raised in generic dask, as it's not implemented for standard dask dataframes either (though it is implemented for dask arrays). It looks like there's been some [previous thinking](https://stackoverflow.com/questions/38760864/how-do-you-transpose-a-dask-dataframe-convert-columns-to-rows-to-approach-tidy) about whether transpose would be efficient on dask dataframes, but I'll raise it again for discussion as I couldn't find any issues specific to transposing dataframes.

**Comment by mrocklin** [comment]
Dask dataframe only partitions along rows.  We won't be able to do this operation effiiciently nor will we be able to store the data efficiently.  

If your data fits in memory then I recommend using just cudf.

If you want to partition along both rows and columns then I recommend using a different project, like Xarray, (which is still Dask accelerated).

**Comment by mrocklin** [comment]
OK to close?
