### ISSUE TITLE
[BUG] Support melt on dataframes

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cudf#209]
### Description
As a user, I'd like to be able to `melt` my dask_cudf dataframes. I can currently do this in cudf dataframes and standard dask dataframes, but not with dask_cudf dataframes.

### Desired Behavior
The equivalent of the following with dask_cudf dataframes:

cuDF:
```
import cudf
sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
print(sample)
print(cudf.melt(sample, id_vars=['a'], value_vars=['b', 'c']))
   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
   a  variable  value
0  1         b      4
1  2         b      5
2  3         b      6
3  1         c      7
4  2         c      8
5  3         c      9
```
Standard Dask:
```
import dask.dataframe as dd
import pandas as pd
from dask.dataframe import melt

sample = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
ddf = dd.from_pandas(sample, npartitions=2)
melt(ddf, id_vars=['a'], value_vars=['b', 'c']).compute()
	a	variable	value
0	1	b	4
1	2	b	5
2	3	b	6
3	1	c	7
4	2	c	8
5	3	c	9
```

### Additional Context
cuDF's `melt` [implementation](https://github.com/rapidsai/cudf/blob/branch-0.7/python/cudf/reshape/general.py#L13) is not a DataFrame method. In pandas, `melt` is both a DataFrame method and a top-level method. Additionally, cuDF dataframes do not have a `pop` method, which appears to be one of the reasons that `dask.dataframe.melt` does not work with cuDF dataframes (though there are likely others, as dask.dataframe.melt is tied to the `.values` in pandas as well).

Dask does not have a DataFrame level `melt` method either, which would probably block any potential pass-through of the cudf `melt` if it were implemented as a DataFrame level method. Dask's [melt](https://github.com/dask/dask/blob/master/dask/dataframe/reshape.py#L234) is hard coded to use pandas's top level melt (pd.melt). I suspect the right approach might be to either to:

1) Create dask-cudf specific DataFrame level melt functionality;
2) Refactor dask's `melt` to be a pass-through that could support `cudf.melt` or `pd.melt`.

<details>
<summary> dask.dataframe.melt with cuDF dataframe </summary>
```
import dask_cudf
import cudf
from dask.dataframe import melt

sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
ddf = dask_cudf.from_cudf(sample, npartitions=2)
melt(ddf, id_vars=['a'], value_vars=['b', 'c']).compute()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    161     try:
--> 162         yield
    163     except Exception as e:

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3739     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3740         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3741 

/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/reshape/melt.py in melt(frame, id_vars, value_vars, var_name, value_name, col_level)
     92     for col in id_vars:
---> 93         id_data = frame.pop(col)
     94         if is_extension_type(id_data):

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0.dev0+345.ga87b8a8f.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py in __getattr__(self, key)
    176 
--> 177         raise AttributeError("'DataFrame' object has no attribute %r" % key)
    178 

AttributeError: 'DataFrame' object has no attribute 'pop'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-33-119281cb81f1> in <module>
      5 sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
      6 ddf = dask_cudf.from_cudf(sample, npartitions=2)
----> 7 melt(ddf, id_vars=['a'], value_vars=['b', 'c']).compute()

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/reshape.py in melt(frame, id_vars, value_vars, var_name, value_name, col_level)
    244                                 value_vars=value_vars,
    245                                 var_name=var_name, value_name=value_name,
--> 246                                 col_level=col_level, token='melt')

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    566         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    567         """
--> 568         return map_partitions(func, self, *args, **kwargs)
    569 
    570     @insert_meta_param_description(pad=12)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   3777 
   3778     if meta is no_default:
-> 3779         meta = _emulate(func, *args, udf=True, **kwargs2)
   3780     else:
   3781         meta = make_meta(meta, index=meta_index)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3738     """
   3739     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3740         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3741 
   3742 

/conda/envs/rapids/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    177                 "{2}")
    178         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 179         raise ValueError(msg)
    180 
    181 

ValueError: Metadata inference failed in `melt`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'DataFrame' object has no attribute 'pop'")

Traceback:
---------
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py", line 162, in raise_on_meta_error
    yield
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py", line 3740, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/reshape/melt.py", line 93, in melt
    id_data = frame.pop(col)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0.dev0+345.ga87b8a8f.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 177, in __getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
```
</details>

**Comment by mrocklin** [comment]
If we had those methods on cudf, do you think that things would work?  If
so, any interest in getting your hands dirty with cudf?  It sounds like
those changes might be fairly straightforward to implement.

**Comment by kkraus14** [comment]
> If we had those methods on cudf, do you think that things would work? If so, any interest in getting your hands dirty with cudf? It sounds like those changes might be fairly straightforward to implement.

+1 to this. We should strive to match Pandas compatibility in cuDF instead of adding more custom code to dask-cudf where possible.

@beckernick if you raise an issue with the missing functionality for cuDF I'll be happy to help work through it with you.

**Comment by beckernick** [comment]
Happy to @kkraus14. Not trying to pass the buck despite filing a lot of issues today 😄 

@mrocklin , I tested including melt as a dataframe level method for cudf and wrote a simple .pop() method as well. I still ran into issues with the pass-through due to dask expecting a `.values` accessor for the underlying data. If we create a .values property to return the underlying data buffer, perhaps? WE can try that. We can also cross this bridge when we come to it though, as like Keith said we should be aiming to match pandas.

**Comment by mrocklin** [comment]
Is this the dask dataframe code that we're running into?

```python
def melt(frame, id_vars=None, value_vars=None, var_name=None,
         value_name='value', col_level=None):

    from dask.dataframe.core import no_default

    return frame.map_partitions(pd.melt, meta=no_default, id_vars=id_vars,
                                value_vars=value_vars,
                                var_name=var_name, value_name=value_name,
                                col_level=col_level, token='melt')
```

If so you might consider switching out the `pd.melt` function with something more generic.  One way to do this is that if `pd.melt(df, ...)` is the same as `df.melt(...)` then we might consider swapping out `pd.melt` in the dask code above with a function that calls a method, something like
'
'    lambda df, **kwargs: df.melt(**kwargs)

The way we usually do this is with the `M` methodcaller object, which is nicer than a lambda for us for a few internal reasons.  So, something like this might work:

```diff
+from ..utils import M

...

-    return frame.map_partitions(pd.melt, meta=no_default, id_vars=id_vars,
+    return frame.map_partitions(M.melt, meta=no_default, id_vars=id_vars,
                                value_vars=value_vars,
                                var_name=var_name, value_name=value_name,
                                col_level=col_level, token='melt')
```

**Comment by beckernick** [comment]
Thanks Matt. Great to learn that common practice in the dask code. Will give this a closer look.

**Comment by mrocklin** [comment]
If true, this would probably remove the need for pop and such in cudf
(though the method would still be necessary).  We were calling the
pandas.melt function on a cudf dataframe, which I wouldn't expect to work.

**Comment by beckernick** [comment]
As an update, using the `M` methodcaller object and updating the API for cudf melt for pandas consistency doesn't quite work. It appears that a None is introduced somewhere and passed to the `make_meta` which ultimately causes a cudf error. Investigating more.

**Comment by beckernick** [comment]
With https://github.com/rapidsai/cudf/pull/1413 merged, when https://github.com/dask/dask/pull/4719 and https://github.com/rapidsai/cudf/pull/1463 are merged we will be all set with this functionality.

**Comment by mrocklin** [comment]
All of those are merged.  Can this be closed?

**Comment by beckernick** [comment]
Looks like we have an outstanding issue with the pass-through due to cudf's melt not having a `col_level` keyword argument. We can probably either implement this as a placeholder that does nothing (and assert that the kwarg is None) or actually implement the functionality now that we have MultiIndex.

**Comment by kkraus14** [comment]
> Looks like we have an outstanding issue with the pass-through due to cudf's melt not having a `col_level` keyword argument. We can probably either implement this as a placeholder that does nothing (and assert that the kwarg is None) or actually implement the functionality now that we have MultiIndex.

I'd suggest you open an issue on cuDF and we continue discussion there 😄

**Comment by beckernick** [comment]
Done :)
