### ISSUE TITLE
Deploying dask-cudf on Python env: Testing rapidsai with dask-cudf

### ISSUE THREAD

**Issue by tobimichigan** [rapidsai/dask-cudf#210]
On Dask GPU Dataframes

A partitioned gpu-backed dataframe, using Dask.
Setup from source

Setup from source repo:

    Install dependencies into a new conda environment

    conda create -n dask-cudf \
       -c rapidsai -c numba -c conda-forge -c defaults \
       cudf dask cudatoolkit

**In your read-me, you were not specific on which options to use, what you specified above looks like a list of options. I had to figure out this myself.**
    Activate conda environment:

    source activate dask-cudf (done)

    Clone dask-cudf repo:  (done)

    git clone https://github.com/rapidsai/dask-cudf 

    Install from source:

    cd dask-cudf  (done)
    pip install . (**_[what???????????]_**)

Test

    Install pytest  (**NO specification given**)

    conda install pytest  (**done**)

    Run all tests:

    py.test dask_cudf   (**from where??????**)

    Or, run individual tests:

     py.test dask_cudf/tests/test_file.py  (**the link to this line is missing**)
![rapidsai_dependencies](https://user-images.githubusercontent.com/5084987/56145407-29a92a80-5f9c-11e9-94db-0fb5eb4bc3e6.png)

![rapidsai_dependencies2](https://user-images.githubusercontent.com/5084987/56146213-c1f3df00-5f9d-11e9-91cc-55af03bf8595.png)

pip install pre-commit  (**please kindly elaborate further**)
pre-commit install (**please kindly elaborate further)**

I am quite interested on this repo and I would love to be an active contributor. I am on a 2 core CPU or is this repo only for GPU processors?

**Comment by quasiben** [comment]
Thanks for the interest @tobimichigan .  It looks like you are trying to install on a Windows machine.  Unfortunately, we only support Linux at the moment (Ubuntu/Centos).  I would recommend taking a look at the rapids home page for information on installing with conda and/or docker:
https://rapids.ai/start.html

**Comment by tobimichigan** [comment]
Oh, I see, everyone seems to be avoiding Microsoft in this every growing Machine Learning. Well guess I would just have to save up and buy a new system for Linux purposes...and yea, "The RAPIDS data science framework includes a collection of libraries for executing end-to-end data science pipelines completely in the GPU." seems to nail it too. I have plans in the making to procure a GPU based system soon.

**Comment by quasiben** [comment]
Yes, unfortunately for much of the GPU datascience ecosystem only Linux is supported.  Still, I would encourage you to look at [Scikit Learn](https://scikit-learn.org/stable/) and [Dask](https://dask.org/) for scalable machine learning
