### ISSUE TITLE
[FEA] dask-cudf should support multi-file read_orc

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#217]
Breaking out the feature request for read_orc from the [original issue](https://github.com/rapidsai/dask-cudf/issues/108)

This feature request should be doable once [cudf.read_orc](https://github.com/rapidsai/cudf/pull/1466) lands

**Comment by mrocklin** [comment]
cc @quasiben this may interest you

**Comment by quasiben** [comment]
yup, sounds good

**Comment by quasiben** [comment]
https://github.com/rapidsai/cudf/pull/1466 is merged and I am now working on this

**Comment by mrocklin** [comment]
This seems to be resolved
