### ISSUE TITLE
Write failed with dask_cudf.to_csv()

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/dask-cudf#221]
I got errors when using dask_cudf.to_csv(). I tried writing my dask_cudf dataframe into a .csv file but it failed.

Here is an unit test.

```python
from numba import cuda
from dask_cudf import from_delayed
from dask.delayed import delayed
from cudf import DataFrame

if __name__ == '__main__' :
    from dask_cuda import LocalCUDACluster
    cluster = LocalCUDACluster()
    
    from dask.distributed import Client
    client = Client(cluster)

    df = from_delayed([
        delayed(DataFrame)({'a': range(i, i+5)})
        for i in range(0, 25, 5)
    ])
    df.to_csv('result-*.csv', index=False)
```
When I run above the code, I got the errors.
```
 Function:  execute_task
    args:      ((<function apply at 0x7fdea43446a8>, <function _write_csv at 0x7fddaa4fe598>, [<cudf.DataFrame ncols=1 nrows=5 >, <dask.bytes.core.OpenFile object at 0x7fddaa43f898>], (<class 'dict'>, [['index', False]])))
    kwargs:    {}
    Exception: AttributeError("'DataFrame' object has no attribute 'to_csv'")''
```
I appreciate if anyone has any suggestions.

**Comment by mrocklin** [comment]
dask-cudf doesn't implement everything that dask dataframe does.  Unfortunately this is in that set of things.  @randerzander there is a doc somewhere that lays out the situation 

https://rapidsai.github.io/projects/cudf/en/0.7.0/dask-cudf.html

**Comment by MikeChenfu** [comment]
Thanks @mrocklin . 
I see that dask_cudf supports to_csv api so I try it. That document is very helpful.
