### ISSUE TITLE
[QST] How to eliminate/drop 0 row partitions?

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#236]
I have an ETL process which filters different counts of records on a per input-file basis.

I end up with a dask-cudf DataFrame where many of my partitions contain 0 rows. This presents a problem for APIs that consume partitions of my DataFrame downstream, dask-xgboost for instance.

I'm aware of the `repartition` operator and its "npartitions" operator, which works in testing, but I essentially have to guess and check the number of partitions that results in a merge in which no partitions have 0 rows.

Is there an easy way to drop, or force merging of 0-length partitions?

**Comment by mrocklin** [comment]
There is no way to do this lazily, but if you're fine computing you could probably do something like this:

```python
lengths = df.map_partitions(len).compute()
nonempty = [length > 0 for length in lengths]
df = df.partitions[nonempty]
```
