### ISSUE TITLE
[Bug] read_csv(/foo/file_*) fails if only one file is in the directory. 

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/dask-cudf#237]
When using a wildcard to read in files, if there is only one file in the directory, `dask_cudf.read_csv()` fails and returns a "file not found error." Full stack trace below: 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-99fd2144cdec> in <module>
      1 # years >= 2015 data has different column names
      2 # remap to match existing schema
----> 3 newer_df = dask_cudf.read_csv('/data/nyc-taxi/2015/yellow_tripdata_2015-1*')
      4 
      5 # data for 2015+ has more columns

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0.0.0.dev0-py3.7.egg/dask_cudf/io/csv.py in read_csv(path, chunksize, **kwargs)
     18         return func(path, blocksize=chunksize, **kwargs)
     19     else:
---> 20         return _internal_read_csv(path=path, chunksize=chunksize, **kwargs)
     21 
     22 

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0.0.0.dev0-py3.7.egg/dask_cudf/io/csv.py in _internal_read_csv(path, chunksize, **kwargs)
     28     if not filenames:
     29         msg = f"A file in: {filenames} does not exist."
---> 30         raise FileNotFoundError(msg)
     31 
     32     name = "read-csv-" + tokenize(

FileNotFoundError: A file in: [] does not exist.```

**Comment by mrocklin** [comment]
Looking at the traceback it looks like it's pointing us to this code

https://github.com/rapidsai/dask-cudf/blob/db258ab1304d5a7d4fe2af659f6d100d33c56671/dask_cudf/io/csv.py#L23-L30

It looks like `sorted(glob(str(path)))` is returning an empty result.  I recommend trying this and seeing what that happens.  If that returns no results then my guess is that there aren't any files that match your glob string.

**Comment by quasiben** [comment]
Hmm, I just tried this without issue:

```python
In [8]: ddf = dask_cudf.read_csv('/home/nfs/bzaitlen/TEST_CSV/*')

In [10]: ddf = dask_cudf.read_csv('/home/nfs/bzaitlen/TEST_CSV/exampl*')
```

```
(cudf-dev) bzaitlen@dgx16:~/TEST_CSV$ ls ~/TEST_CSV/
example.csv
```

Could it be the path is incorrect ?  As a guess, can you try:
> /datasets/nyc_taxi/2015/yellow_tripdata_2015-1*

**Comment by robocopnixon** [comment]
I'll try @mrocklin suggestion when I get a chance. The path is correct, and I made sure the file could be read by the notebook. I repo'd this twice before posting, and `pandas.read_csv()` could find the file.

**Comment by mrocklin** [comment]
I recommend trying the python `glob` module (which is what Dask is using here to find filenames) and see if the problem persists there.

**Comment by robocopnixon** [comment]
User error. Thanks everyone.
