### ISSUE TITLE
[BUG] Dependency mismatch & probably incorrect

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/dask-cudf#246]
The conda `meta.yaml` specifies dask >=0.19.0 and distributed >=1.23.0

`requirements.txt` specifies dask>=1.1 and distributed>=1.26

These dependencies should match. Additionally, I think these versions are too old and should be updated.

My guess at the versions:
- dask>=1.1.5 (?)
- distributed>=1.28.0.

**Comment by mrocklin** [comment]
@quasiben can you handle this?  Given that dask-cudf is likely to be used only by early adopters, and that there is fairly tight coupling, my inclination is just to move everything to be pretty recent.  I might go even newer and use latest release at dask==1.2.2

**Comment by kkraus14** [comment]
I would suggest dask >=1.2.2 so that we quickly realize if things upstream break us with new releases 😄
