### ISSUE TITLE
dask cudf records being manipulated in map_partitions call

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/dask-cudf#260]
map_partitions seems to be manipulating the input data frame with 'foo' or either is running some sort of unit-test before running the actual mapper function. 

Below is my code:

```
import dask_cudf

def new_to_ipv6(df):
    print(df.head())
    s = df['network'].data
    s = s.split('.')
    o1 = s[0]
    o2 = s[1]
    o3 = s[2]
    o4 = s[3]
	.
	.
	.
	.
	
dsk_df = dask_cudf.read_csv('net.csv')
print(dsk_df.head())
print(dask_cudf.__version__)
dsk_df = dsk_df.map_partitions(new_to_ipv6)


```

Output:

```
   network
0  a.b.c.d
1  b.d.e.f
2  c.d.x.z
0.8.0a1+132.g2f36e57.dirty
   network
0      foo
1      foo

```
![dask_bug](https://user-images.githubusercontent.com/11664259/58271989-03249f00-7d53-11e9-90a6-a0c68e3df837.PNG)

This issue surfaced while I was trying to access specific index of the output of `df['network'].data.split('.')` and dask-cudf error's out saying index can't be accessed(which is true because there is no record at index 1 since 'foo' is being inserted. Or to me it looks more like some unit-test is running rather than records being inserted.

One more observation, I don't see this issue in dataset which has integer/floats..Tried on mnist dataset and don't see this kind of behavior. When I have string column, I see this issue. 

csv file : [net_dump_dash.zip](https://github.com/rapidsai/dask-cudf/files/3213359/net_dump_dash.zip)

**Comment by quasiben** [comment]
Thanks @galipremsagar for reporting! 

`map_partitions` does do a kind of test, that is, it's trying to match the output metadata.  Users can supply this information with kwarg `meta` (see: http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) .   when `meta` is not supplied dask tries to infer the output and in this case it builds a small DataFrame with `foo` as the fake string.  You can read more up on this particular issue here:

https://github.com/dask/dask/issues/2265#issuecomment-297802822

The quick answer your problem is to do the following: `meta='O'`

```python
In [32]: def new_to_ipv6(df):
    ...:     print(df.head())
    ...:     s = df['network'].data
    ...:     s = s.split('.')
    ...:     o1 = s[0]
    ...:     o2 = s[1]
    ...:     o3 = s[2]
    ...:     o4 = s[3]
    ...:
    ...:     return o1, o2, o3, o4
    ...:
    ...:

In [33]: res = ddf.map_partitions(new_to_ipv6, meta=('O')).compute()
   network
0  a.b.c.d
1  b.d.e.f
2  c.d.x.z

In [34]: res[0][0].to_host()
Out[34]: ['a', 'b', 'c']
```

**Comment by quasiben** [comment]
@galipremsagar if you are not aware [cyberpandas](https://github.com/ContinuumIO/cyberpandas/) may also be of use to you in the future:
https://cyberpandas.readthedocs.io/en/latest/

**Comment by galipremsagar** [comment]
> Thanks @galipremsagar for reporting!
> 
> `map_partitions` does do a kind of test, that is, it's trying to match the output metadata. Users can supply this information with kwarg `meta` (see: http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) . when `meta` is not supplied dask tries to infer the output and in this case it builds a small DataFrame with `foo` as the fake string. You can read more up on this particular issue here:
> 
> [dask/dask#2265 (comment)](https://github.com/dask/dask/issues/2265#issuecomment-297802822)
> 
> The quick answer your problem is to do the following: `meta='O'`
> 
> ```python
> In [32]: def new_to_ipv6(df):
>     ...:     print(df.head())
>     ...:     s = df['network'].data
>     ...:     s = s.split('.')
>     ...:     o1 = s[0]
>     ...:     o2 = s[1]
>     ...:     o3 = s[2]
>     ...:     o4 = s[3]
>     ...:
>     ...:     return o1, o2, o3, o4
>     ...:
>     ...:
> 
> In [33]: res = ddf.map_partitions(new_to_ipv6, meta=('O')).compute()
>    network
> 0  a.b.c.d
> 1  b.d.e.f
> 2  c.d.x.z
> 
> In [34]: res[0][0].to_host()
> Out[34]: ['a', 'b', 'c']
> ```

Cool, This helped.



> @galipremsagar if you are not aware [cyberpandas](https://github.com/ContinuumIO/cyberpandas/) may also be of use to you in the future:
> https://cyberpandas.readthedocs.io/en/latest/

Yes I'm aware of that package. Been using it.

**Comment by quasiben** [comment]
Glad to hear it!  I'm going to close this issue.
