### ISSUE TITLE
[BUG] Agg function on Multi column groupby throws following errors. 

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/dask-cudf#263]
**Multi Column Group-by throws following error**: "Length of values does not match index length"

**Reproducer Code:**
```
from cudf import DataFrame
import dask_cudf
import numpy as np

ddf = DataFrame()
ddf['key'] = [0, 0, 1, 1, 2, 2, np.NaN]
ddf['val'] = [0, 1, 2, 3, 4, 5, 6]

df = dask_cudf.from_cudf(ddf, npartitions=2)
df['mult'] = df['key'] * df['val']
df = df.fillna(0)
print(df.compute())

groups = df.groupby(['key', 'val'])
res = groups.agg({"mult":"mean"})
```
if you change the agg function from mean to sum, it throws another error: 
```
res = groups.agg({"mult":"sum"})
```
AttributeError("'RangeIndex' object has no attribute 'names'")

**Comment by quasiben** [comment]
Thanks for the bug report and reproducible example.  This is a bug.  While we fix the `mean()` call should work on all columns in the dataframe:

```python
groups.mean()
```

**Comment by quasiben** [comment]
With https://github.com/rapidsai/cudf/pull/1896/ merged in we are now getting a new error:

```
~/GitRepos/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    170                 "{2}")
    171         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 172         raise ValueError(msg)
    173
    174

ValueError: Metadata inference failed in `_groupby_apply_funcs`.
```

**Comment by quasiben** [comment]
@thomcom I wonder if `_sanitize_values` is flummoxed by some the nonmeta dataframes ?

**Comment by quasiben** [comment]
@thomcom and I just finished a debug session.  There is a small error in cudf which we are resolving now and PR is incoming

**Comment by thomcom** [comment]
Curse string iteration!!!!!

**Comment by quasiben** [comment]
With https://github.com/rapidsai/cudf/pull/1902 this issue has been fixed.  Thanks @thomcom and thanks @mlahir1 for reporting
