### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by heshanshanhg3** [rapidsai/dask-cudf#268]
dask-cudf  need cuda Version must be cuda 9.2 or cuda 10.0 ? this have to change cuda vesrion。 High cost。can more cuda version use on dask-cudf,for example cuda 9.0?

**Comment by quasiben** [comment]
@heshanshanhg3 , I believe dask-cudf only support cuda 9.2 and 10.0.  This is because cudf only supports 9.2 and 10.0.  I suspect this is because of critical features in 9.2/10.0 required for libcudf

**Comment by kkraus14** [comment]
There are additional atomics available in CUDA 9.2 and newer that we take advantage of in cuDF, where supporting them in older versions would have significant performance impact, so we've made the decision to only support CUDA 9.2 and newer.

**Comment by quasiben** [comment]
Thanks for the response @kkraus14
