### ISSUE TITLE
cudatoolkit version in install instructions

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cudf#271]
I realize this repo is going to be merge with cudf core soon, but I figured this could be something to be addressed before that happens. `README.md` suggests the following:

```
conda create -n dask-cudf \
   -c rapidsai -c numba -c conda-forge -c defaults \
   cudf dask cudatoolkit
```

This will by default install `cudatoolkit=10`, even if the target machine uses 9.2. The errors you get are not very helpful for that situation, mostly RMM allocation errors.

So my suggestion is that the instruction also describes the appropriate version of `cudatoolkit` must be installed.

**Comment by jakirkham** [comment]
Have you tried with `conda` 4.7? Am curious if PR ( https://github.com/conda/conda/pull/8267 ) is constraining `cudatoolkit` version to align with the driver version correctly.

**Comment by pentschev** [comment]
No, I didn't know about it, will definitely try it out too. Just out of curiosity, [RAPIDS Getting Started](https://rapids.ai/start.html) still asks which CUDA toolkit you're using, is there an intent to drop that? I think here would be good to have the instructions aligned to that of the getting started page.

**Comment by jakirkham** [comment]
It's very new still. Though it would be great to start dogfooding. 🙂

Probably worth making sure it is working correctly in a few cases before advertising more broadly.

Also this is the latest release of Conda. Many people are likely still on old versions.

Back to your original point, it seems reasonable to note this in the README or in some more general cross project documentation as well.
