### ISSUE TITLE
[BUG] Multi Column Group-by fails with following error in dask_cudf while works fine in cudf

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/dask-cudf#273]
**Multi Column Group-by throws following error**: "AttributeError: 'RangeIndex' object has no attribute 'names'".  

dask_cudf
----------
**Reproducer Code:**
```
from cudf import DataFrame
from numpy.random import randint
import numpy as np

df = DataFrame({
    'a': randint(60000000,280000000,1000) ,
    'b': randint(-2,2,1000),
    'c': randint(0,5,1000)
})

import dask_cudf
data = dask_cudf.from_cudf(df, npartitions=100)

glist= list(data.head().a)
df_glist = DataFrame()
df_glist['a'] = glist
data = data.merge(df_glist, how='inner', on='a')

res = data.groupby([data.a, data.b]).sum()

df_res = DataFrame()
df_res = res.compute()

```
CUDF
----------
same functionality written in cudf, we get expected results.
```
from cudf import DataFrame
from numpy.random import randint
import numpy as np

data = DataFrame({
    'a': randint(60000000,280000000,1000) ,
    'b': randint(-2,2,1000),
    'c': randint(0,5,1000)
})

glist= list(data.head().a)
df_glist = DataFrame()
df_glist['a'] = glist
data = data.merge(df_glist, how='inner', on='a')

res = data.groupby([data.a, data.b]).sum()

print(res.to_pandas())
```

**Comment by quasiben** [comment]
@mlahir1 yup, this is a bug.  I think this is on the cudf side.  I'm seeing the error here:

```
In [10]: %debug
> /home/nfs/bzaitlen/GitRepos/cudf/python/cudf/groupby/groupby.py(121)__init__()
    119                 self._by = []
    120                 # guard against missing MI names
--> 121                 if self._df.index.names is None or sum(
    122                         x is None for x in self._df.index.names) > 1:
    123                     self._df.index.names = list(
```

@thomcom should `self._df.index.names` be `self._df.index.name` ?

**Comment by thomcom** [comment]
An MI has a names attribute instead of a name - this error says that a RangeIndex is getting into this portion of logic where the groupby level is >=1 or a list. Thanks for the Issue @mlahir1 I will be looking into it.

**Comment by quasiben** [comment]
Ah!  Apologies @thomcom !

**Comment by randerzander** [comment]
@thomcom is there a related cuDF issue already open?

**Comment by mlahir1** [comment]
@randerzander This issue still exists. I have checked with latest branch-0.8 code.

**Comment by randerzander** [comment]
@mlahir1 I just tried this from tip of branch-0.9 and looks resolved there.

Please re-open if you still see this issue.

**Comment by mlahir1** [comment]
@randerzander Thanks Randy. Checked it and It is resolved.
