### ISSUE TITLE
read_csv fails with multi-node & single large file

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/dask-cudf#277]
The following code worked fine and I was able to perform operations when I was running dask on a single machine only. 

```
import dask_cudf
from dask.distributed import Client
client = Client(scheduler_file='/myhome/newfile')
master_df = dask_cudf.read_csv("/pathto/large.file",sep='|')
```

But when I started using multi-node and trying to read a single csv file I see the below exception. The setup is using two T4 server machines with 4 T4's in each one of them. Each T4 is 16GB. I see that the GPU usage of one process goes in steps of 0GB -> 4GB -> 8GB -> process killed. In the jupyter logs I see the OOM exception:

```
[W 22:43:51.600 LabApp] Notebook Notebooks_NERSC-pipeline.ipynb is not trusted
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory
[I 22:44:57.420 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 9d787116-dd70-43d5-b52b-1c0be17d3b01 restarted
[I 22:45:31.498 LabApp] Kernel shutdown: 9d787116-dd70-43d5-b52b-1c0be17d3b01
```

Probably can't share the dataset publicly but you can ping me on slack so that I can help getting you access to the file. 

Observations:
1. This issue doesn't surface if I have many csv files. (All csv's combined have 2Billion records)
2. I've tried narrowing down the number of records in a single file and this was the observation:

| Number of Records | File size | Issue occurs |
| ------------- | ------------- | ------------- |
|1075366480 (1.075 Billion)  | 270GB  | yes |
|250000000 (250 million)  | 62GB  | yes |
|50000000 (50 million)  | 13GB  | yes |
|20000000 (20 million) | 5GB | yes |
|15000000 (15 million) | 4GB | no |
|10000000 (10 million)  | 3GB  | no |

**Comment by quasiben** [comment]
can you try with a prefix of `file://`  -- this uses `cudf.read_csv` directly and will read the entire file(s) at once compared with a distributed read

**Comment by quasiben** [comment]
Apologies, I'm incorrect.  @mrocklin corrected me:

> This still chunks things, it just uses Dask's standard chunking mechanism and so uses host memory.

the standard behavior of dask_cudf.read_csv is to keep things in GPU memory as much a possible -- using `file://` will chunk with host memory then move to device

**Comment by quasiben** [comment]
If the file is quite large you might want to change the chunksize:

> dask_cudf.read_csv(file, chunksize="512 MiB")

The default is `256 MiB`

**Comment by randerzander** [comment]
I believe this was resolved by updating the version of dask_cudf (from 0.7.x to 0.8.x) in the container being used.

Please re-open if the issue resurfaces
