### ISSUE TITLE
[BUG] dask_cudf.read_orc doesn't handle remote filesystems

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#282]
When attempting to dask_cudf.read_orc from hdfs, for instance, dask_cudf tries to read metadata from one of the files in the glob, but [assumes this file is available locally](https://github.com/rapidsai/dask-cudf/blob/branch-0.8/dask_cudf/io/orc.py#L29).

It seems like dask_cudf.read_orc should be updated to follow the pattern that dask_cudf.read_csv follows, which would enable dask_cudf.read_orc to work with HDFS and cloud storage systems.

**Comment by mrocklin** [comment]
Can we pass a block of bytes to `cudf.read_orc` ?  If not, that's probably the first step here.

**Comment by richardulrich** [comment]
In read_csv the URL is handled via the following:

if "://" in str(path):
        func = make_reader(cudf.read_csv, "read_csv", "CSV")
        return func(path, blocksize=chunksize, **kwargs)
    else:
        return _internal_read_csv(path=path, chunksize=chunksize, **kwargs)

in read_orc it does the following:

  filenames = sorted(glob(str(path)))
    name = "read-orc-" + tokenize(path, **kwargs)

    meta = cudf.read_orc(filenames[0], **kwargs)

Wouldnt we just need to make read_orc behave more like read_csv, that or have a indicator passed to each of the apis that tells it whether the file is local or remote?

**Comment by mrocklin** [comment]
Yes, however the `cudf.read_csv` function accepts a Python `bytes` object as an input, while looking at the `cudf.read_orc` code I suspect that it expects to be given a filename.  Once that's done it becomes fairly easy for Dask to handle the bytes-handling with it's current system (which gives you connections to gcs/s3/hdfs/adl) and then hand off those bytes to ORC.  You lose out on a host-device memory copy, but relative to the cost of remote access that's probably not a problem.

cc @mjsamoht 

Also, it's worth pointing out that when reading from remote systems we're almost certainly bottlenecked by network bandwidth anyway.  I wouldn't expect a native `dask_cudf.read_orc` to be any faster than the following:

```python
dask.dataframe.read_orc(...).map_partitions(cudf.from_pandas)
```

**Comment by mjsamoht** [comment]
cc @j-ieong @OlivierNV 

What exactly is needed here?  Just add support for Python `bytes` object as input?  Or support for byte ranges in order to split work across multiple GPUs?  The former is fairly easy, the latter is not because we would always need the metadata.  Instead of byte streams, it would be better to use the existing support for row groups/stripes to break up the workload.

**Comment by mrocklin** [comment]
We will never ask you for byte ranges in parquet or orc.  To start, the ask here is your first case, given the bytes of a complete orc file, give us a cudf.  Eventually we may also ask to read a particular row group/stripe, given the bytes for that row group/stripe + metadata, but that isn't what is being asked for now.

**Comment by OlivierNV** [comment]
Yes we need to add support for memory buffer input (IIRC, the api is already here, but is not support for orc/parquet). stripe/rowgroup selection is already supported so will automatically work with memory buffer (downside is that we still need the entire file for metadata) ~ long term, we should add some kind of random access file interface or just support remote filesystems through Arrow.

**Comment by randerzander** [comment]
@OlivierNV can we get a cuDF issue opened for tracking? We need to do this early in 0.9, please.

**Comment by mjsamoht** [comment]
Filed new issue https://github.com/rapidsai/cudf/issues/2043

**Comment by randerzander** [comment]
@rjzamora can you take a look at whether we can fix this now that rapidsai/cudf#2043 is resolved?

Can you also check that remote filesystems are working for dask_cudf.read_parquet? I believe they would also have been affected

**Comment by mrocklin** [comment]
On the dask side we probably want to use https://docs.dask.org/en/latest/bytes.html#dask.bytes.read_bytes , probably with `blocksize=None`.

**Comment by mlahir1** [comment]
@randerzander with https://github.com/rapidsai/cudf/issues/2043 this resolved I am using the following code to read the orc files from HDFS. 
```
def read_hdfs_orc_bytes(fname,cols):
    fs = pa.hdfs.connect(host=host, port=port, user=user, kerb_ticket="/tmp/krb5cc_0")
    with fs.open(fname, 'rb') as f:
        buffer = BytesIO(f.read())
        df = cudf.read_orc(buffer, columns=cols)
        return df
```

The problem with this is it still copies all the bytes over over to the GPU until read_orc reads the required columns. We need to eliminate the step of reading all the bytes over to the GPU while reading files from remote files systems as that could have good impact on the speedup.

**Comment by quasiben** [comment]
Looking at this now

**Comment by quasiben** [comment]
I naively played with cudf.read_orc and read_bytes and I'm getting errors:

```python
sample, blocks = dask.bytes.read_bytes(url, blocksize=None) 
chunks = list(dask.core.flatten(blocks))
_chunks = dask.compute(chunks)
cudf.read_csv(_chunks[0][0])
```

This leads to the following error:
```
~/GitRepos/cudf/python/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, comment, na_values, keep_default_na, na_filter, prefix, index_col)
     55         na_filter=na_filter,
     56         prefix=prefix,
---> 57         index_col=index_col
     58     )
     59

~/GitRepos/cudf/python/cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_read_csv()

~/GitRepos/cudf/python/cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_read_csv()

~/miniconda3/envs/cudf-dev/lib/python3.7/genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except OSError:
     32         return False

ValueError: stat: embedded null character in path
```

**Comment by quasiben** [comment]
Actually, what I wrote above is incorrect

**Comment by mrocklin** [comment]
@mlahir1 question, what would happen if you passed the Python file-like object, `f`, directly into `cudf.read_orc`?

```python
    with fs.open(fname, 'rb') as f:
        df = cudf.read_orc(f, columns=cols)
```

My guess is that this wouldn't work today, and that it would be a little unpleasant to make work on the C++ side (that code would need to call Python methods) but that's probably the cleanest solution here?

**Comment by mrocklin** [comment]
Something like this will also probably come up with Parquet

cc @mjsamoht

**Comment by quasiben** [comment]
Just tested this and it all works fine!

```python
In [78]: fs = HTTPFileSystem()

In [79]: with fs.open(url, 'rb') as f:
    ...:     df = cudf.read_orc(f, columns=['articleID', 'articleWordCount'])
    ...:

In [80]: df.head().to_pandas()
Out[80]:
                  articleID  articleWordCount
0  58def1347c459f24986d7c80               716
1  58def3237c459f24986d7c84               823
2  58def9f57c459f24986d7c90               575
3  58defd317c459f24986d7c95              1374
4  58df09b77c459f24986d7ca7               708
```

where `url` is a local url using `http.server`

**Comment by mrocklin** [comment]
Oh great.  In that case we probably want to use not `dask.bytes.read_bytes`, but `dask.bytes.open_files`

https://docs.dask.org/en/latest/bytes.html?highlight=open_file#dask.bytes.open_files

We're still assuming that you don't care to chunk within an ORC file, but that should provide a bunch of file-like objects on which you can then call `cudf.read_orc`.

**Comment by mrocklin** [comment]
That should provide a list of serializable file-like-things.  You can then make a task for each one, something like (simplified)

```python
dsk = {(name, i): (cudf.read_orc, f, ...) for i, f in enumerate(open_files(path))}
```

**Comment by quasiben** [comment]
with `open_files` I get the following error:

```python
meta = cudf.read_orc(open_files(path)[0], **kwargs)                                                                                                                               
*** TypeError: stat: path should be string, bytes, os.PathLike or integer, not OpenFile
```

I believe this is failing because down in the Cython of cudf cpp_read_orc calls:
> os.path.isfile(filepath_or_buffer)

This fails on a `dask.bytes.core.OpenFile object` .

**Comment by mlahir1** [comment]
@mrocklin fixing it using "dask.bytes.open_files" would have to copy all the bytes over to the network and then read the required columns. Isn't there a way to just get the bytes of only the specified columns we want to load in to the memory?

I think we will need make same changes in hdfs lib of pyarrow for this functionality.

**Comment by mrocklin** [comment]
Right, so for this approach `cudf.read_orc` would have to happily read file-like objects, by which I mean Python objects with methods like `seek`, `read`, `tell`, `write`.  That was what we were testing with your example in https://github.com/rapidsai/dask-cudf/issues/282#issuecomment-508188221 

I'm curious why it's failing now.

Also cc @martindurant

**Comment by mrocklin** [comment]
> fixing it using "dask.bytes.open_files" would have to copy all the bytes over to the network and then read the required columns. Isn't there a way to just get the bytes of only the specified columns we want to load in to the memory?

Understood.  That's what we're talking about with the open_files approach in the last few comments.

Unfortunately this is difficult because the logic of exactly which bytes to read is something that really only an ORC reader code will be able to tell us, so we have to have Python code that knows about things like HTTP, S3, GCS, Azure interface with C++/CUDA code that knows about exactly which byte ranges to read.

> I think we will need make same changes in hdfs lib of pyarrow for this functionality.

I'm not sure I follow this.  The HDFS PyArrow library provides methods like seed/read/... I'm not sure that it should do anything other than this.

**Comment by quasiben** [comment]
@mrocklin an `OpenFile` object has no attribute for `read` nor `write`

**Comment by martindurant** [comment]
An `OpenFile` must be used in a context `with`

**Comment by martindurant** [comment]
(you could, of course, call `__enter__()` manually, so long as you accept the responsibility to close things later)

**Comment by quasiben** [comment]
@martindurant thanks!  That clears up quite a bit

**Comment by mlahir1** [comment]
@mrocklin Got it.

You are right. Ignore this.
>I think we will need make same changes in hdfs lib of pyarrow for this functionality.

**Comment by quasiben** [comment]
I am waiting for https://github.com/rapidsai/cudf/pull/2160 to be merged then I will follow up with a PR.  I have something which looks like following:

```python
    if "://" in str(path):
        files = open_files(path)s
        with files[0] as fn:
            meta = cudf.read_orc(fn, **kwargs)
        parts = [delayed(_read_orc)(f, **skwargs) for f in files]
        return dd.from_delayed(parts, meta=meta)

def _read_orc(fn, **kwargs):
    with fn as f:
        return cudf.read_orc(f, **kwargs)
```
