### ISSUE TITLE
[BUG] Index name not being set in few operations

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/dask-cudf#284]
There seems to be an inconsistency when we perform operations like `count`, `max`, `min`, `mean`, .. on a groupby. 
dask dataframe, pandas, cudf seem to be consistent in this behavior, but dask cudf dataframe seems to be exhibiting different behavior. We don't seem to be setting index name in the following case:

```python
import cudf
import pandas as pd
import dask
import dask_cudf

df = pd.DataFrame()
df['first_col'] = [0, 0, 1, 1, 2, 2, 2]
df['second_col'] = [0, 1, 2, 3, 4, 5, 6]
ddf = dask.dataframe.from_pandas(df, npartitions=1)
print(ddf.groupby(['first_col']).mean().compute())

	second_col
first_col	
0	0.5
1	2.5
2	5.0

print(ddf.groupby(['first_col']).mean().compute().index.name)
first_col
```
when in case of dask cudf, it is being set to None:
```python
df = cudf.DataFrame()
df['first_col'] = [0, 0, 1, 1, 2, 2, 2]
df['second_col'] = [0, 1, 2, 3, 4, 5, 6]

ddf = dask_cudf.from_cudf(df,npartitions=1)
print(ddf.groupby(['first_col']).mean().compute())

   second_col
0         0.5
1         2.5
2         5.0

print(ddf.groupby(['first_col']).mean().compute().index.name)
None
```

We should ideally be setting the `index.name` to maintain consistent behavior.
Logging this as a dask-cudf issue since it seems to work correctly in cudf.

**Additional context:**
When I do reset index and access the column name, it will result in attribute error
```python
print(ddf.groupby(['first_col']).mean().compute().reset_index()['first_col'])

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-35-3fb071c48e7d> in <module>
----> 1 print(ddf.groupby(['first_col']).mean().compute().reset_index()['first_col'])

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in __getitem__(self, arg)
    269             return self.columns._get_column_major(self, arg)
    270         if isinstance(arg, (str, numbers.Number)) or isinstance(arg, tuple):
--> 271             s = self._cols[arg]
    272             s.name = arg
    273             s.index = self.index

KeyError: 'first_col'
```

cc: @kkraus14 @beckernick @randerzander

**Comment by randerzander** [comment]
@galipremsagar are you able to track this down to an underlying cudf issue?

**Comment by kkraus14** [comment]
@randerzander yes, we are iterating on a solution that will retain names across all index / Series operations.

**Comment by galipremsagar** [comment]
Looks like this is fixed after new groupby changes. Reason is I don't see this issue after reverting my changes made in https://github.com/rapidsai/cudf/pull/2109
Though verifying if there is an issue with other set of operations.

**Comment by galipremsagar** [comment]
@kkraus14 , This seems to be fixed. Do you want me to hold off closing this issue? Otherwise we can go ahead an close this issue as this doesn't reproduce now and this doesn't reoccur with other functionalities around groupby.

**Comment by galipremsagar** [comment]
I'm working on this, Investigating this as I see it happen on nightly. Will check with source as well. If I find the issue persists, will open a PR.

**Comment by galipremsagar** [comment]
I just verified this on source(`branch-0.9`) & on latest nightly, This was an issue with `.agg()` only and was able to reproduce this in two days old nightly builds. 

The issue has gone away:

```python
import cudf
import pandas as pd
import dask
import dask_cudf

df = cudf.DataFrame()
df['first_col'] = [0, 0, 1, 1, 2, 2, 2]
df['second_col'] = [0, 1, 2, 3, 4, 5, 6]

ddf = dask_cudf.from_cudf(df,npartitions=1)
print(ddf.groupby(['first_col']).agg({ "second_col": 'mean'}).compute())
print("------")
print(ddf.groupby(['first_col']).agg({ "second_col": 'mean'}).compute().index.name)

   second_col
first_col
0         0.5
1         2.5
2         5.0
------
first_col
```

Hence closing this issue.
cc: @kkraus14 , @randerzander
