### ISSUE TITLE
Repartition function not implemented

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/dask-cudf#40]
Should follow the dask.dataframe spec of being able to specify `divisions` or `npartitions`, and a flag for `force` which:
"Allows the expansion of the existing divisions. If False then the new divisions lower and upper bounds must be the same as the old divisions."

**Comment by mrocklin** [comment]
So we can reuse the existing methods if we can implement the following in pygdf

1.  Index.is_monotonic
2.  Index.get_slice_bound (for monotonic indexes)
3.  `df[df >= start]` and `df[df <= stop]` (fancy indexing) on Series and DataFrame objects

However, it may also be that this is suboptimal for GPUs.  I'm mostly thinking about code reuse from dask's perspective at the moment.

**Comment by mrocklin** [comment]
Note that `get_slice_bound` may not be necessary if cudf Indexes always claim to be non-monotonic (or None, which might be interpretted as "unknown") . There is already a PR to add `is_monotonic` in cudf, though I've abandoned it.  It would be great if someone else would take it over.

**Comment by kkraus14** [comment]
> Note that `get_slice_bound` may not be necessary if cudf Indexes always claim to be non-monotonic (or None, which might be interpretted as "unknown") . There is already a PR to add `is_monotonic` in cudf, though I've abandoned it. It would be great if someone else would take it over.

`is_monotonic` is set to static `None` for now. I can look into implementing `get_slice_bound` if it's high priority, but the Pandas documentation isn't clear on the expected behaviors, especially regarding `kind : {‘ix’, ‘loc’, ‘getitem’}`

**Comment by mrocklin** [comment]
I suspect that None will suffice

**Comment by randerzander** [comment]
@mrocklin can this be closed now that https://github.com/rapidsai/cudf/pull/958 merged?
