### ISSUE TITLE
Obstacles to code reuse between Dask Dataframe and Dask-GDF

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cudf#41]
Considering issues in #40 and #39 I'm curious what stops us from using existing code in dask.dataframe.  I can think of a few possible answers:

1.  Dask dataframe functions call pandas methods explicitly, like `pandas.concat`, which would coerce data to host memory
2.  Dask GDF uses different metadata than Dask Dataframe (maybe divisions and such are different) and so the old logic won't apply

Are there other things that I'm missing?  If the only issue is the use of pandas functions then I wonder if we might make some of that pluggable and reuse some logic across projects.

Any thoughts @kkraus14 @sklam ?

**Comment by kkraus14** [comment]
@mrocklin There's a number of places where the PyGDF API differs from Pandas, and a large number of places where PyGDF doesn't have the full functionality of Pandas. For general functions it should be nearly plug and play, and in general we can fix many of the inconsistencies where appropriate.

Divisions should likely be the same as we have an index similar to Pandas albeit without multi-indexing. We are slowly moving towards removing indexing other than having a RangeIndex to allow for row number based slicing.

**Comment by kkraus14** [comment]
I would greatly support standardizing the metadata to follow the example of Dask Dataframe to make the user experience of switching between the two and developing shared code for both as painless as possible.

**Comment by mrocklin** [comment]
> There's a number of places where the PyGDF API differs from Pandas, and a large number of places where PyGDF doesn't have the full functionality of Pandas

Are some of these by necessity?  Or is this just because not everything has been implemented yet?  What sorts of APIs differ?

I'm inclined to try to make Dask GDF's classes inherit from Dask Dataframe's classes, changing both where necessary to see if that can happen.  I suspect that this has about a 50/50% chancce of being feasible.

**Comment by mrocklin** [comment]
This has been resolved in #48
