### ISSUE TITLE
Follow cudf with version numbers

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cudf#61]
It looks like the only tag is 0.0.1.  @randerzander recommended that we follow cudf versions.  

I'll plan to do this on the next release, though given stability issues I'm not sure when that release might be.  I'm inclined not to promise anything until 0.6.  @randerzander any concerns with this?

**Comment by datametrician** [comment]
Why does dask-cuDF have to follow cuDF numbering?

**Comment by randerzander** [comment]
It doesn't _have_ to follow cuDF's numbering, but a similar version numbering scheme would make it clearer to users which versions of cuDF and dask_cudf would work together.

@mrocklin no concerns from me

**Comment by randerzander** [comment]
Closing now that we do this
