### ISSUE TITLE
Creating dask_cudf df w/ from_delayed is missing data

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#63]
Possibly related to #62 

Create two dummy CSV files and read them into a dask_cudf:
```
files = ['test1.csv', 'test2.csv']
lines = ['num0,num1', '0,1', '2,3']

for file in files:
    with open(file, 'w') as fp:
        fp.write('\n'.join(lines)+ '\n')

@delayed
def load_file(fn, names, dtypes, skiprows):
    return cudf.read_csv(fn, names=names, dtype=dtypes, skiprows=skiprows)

# csv columns
names = ["num0", "num1"]
dtypes = ["int" for name in names]
df = dask_cudf.from_delayed([load_file(fn, names, dtypes, 1) for fn in files])
print(df.head())
```

Result:
```
  num0 num1
0    0    1
1    2    3
```

Expected Result:
```
  num0 num1
0    0    1
1    2    3
2    0    1
3    2    3
```

**Comment by mrocklin** [comment]
See the npartitions keyword of
http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.head

**Comment by mrocklin** [comment]
So if you were to call `df.compute()` you would likely find that all of the data was there.

**Comment by randerzander** [comment]
Ah, didn't realize .head reads from a single partition by default. Thanks!

**Comment by mrocklin** [comment]
It sounds to me like you didn't get a warning when you did this, which is
slightly concerning.  I thought we warned at runtime when this occurred.
