### ISSUE TITLE
dask-cudf chunks do not appear to follow one-process-per-GPU semantics

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/dask-cudf#68]
I am having trouble producing OPG in dask-cudf. I am running a test notebook and all of the chunks in my dask-cudf appear to be staying pinned to the same device. I am likely doing something incorrectly; maybe in the creation of the dask-cudf dataframe? This is important since dask-cuml is going to be processing the dask-cudf downstream and we will need to be able to test this end-to-end.

```
import cudf
import dask_cudf

from dask.distributed import Client
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster(threads_per_worker = 10)
client = Client(cluster)

X_df = dask_cudf.from_cudf(cudf.DataFrame([('a', [0, 1, 2, 3, 4])]), chunksize=1).persist()
client.who_has()

import numba.cuda
import cuml
def print_device(arr):
    print(str(numba.cuda.get_current_device()))
    print(str(cuml.device_of_ptr(arr.as_gpu_matrix(order="F"))))
    
[client.submit(print_device, part) for part in X_df.to_delayed()]
```

The following is printed in my notebook:
```
{"('from_cudf-168a30423f834eb583d05f58476a4a21', 0)": ('tcp://127.0.0.1:40458',),
 "('from_cudf-168a30423f834eb583d05f58476a4a21', 1)": ('tcp://127.0.0.1:45874',),
 "('from_cudf-168a30423f834eb583d05f58476a4a21', 2)": ('tcp://127.0.0.1:40458',),
 "('from_cudf-168a30423f834eb583d05f58476a4a21', 3)": ('tcp://127.0.0.1:45874',)}

[<Future: status: pending, key: print_device-04d74ae726f4b1b69ed002d269adcc39>,
 <Future: status: pending, key: print_device-0e818733563b55b50320f5092e702aad>,
 <Future: status: pending, key: print_device-9554966353a4b87a1eaecc7981789320>,
 <Future: status: pending, key: print_device-ceb77fd940e635c284f907f0980c913f>]
```

And the following is printed on my workers:

```
<CUDA device 0 'b'Quadro GV100''>
<CUDA device 0 'b'Quadro GV100''>
<CUDA device 0 'b'Quadro GV100''>
0
0
<CUDA device 0 'b'Quadro GV100''>
0
0
```
`nvidia-smi` does show that my workers are all on device 0:

```
|    0     29507      C   /share/conda/cuml/bin/python                 447MiB |
|    0     29537      C   /share/conda/cuml/bin/python                 447MiB |
|    0     29538      C   /share/conda/cuml/bin/python                 447MiB |
```

Another test I did was running my own `dask-mpi` cluster and manually setting the CUDA_VISIBLE_DEVICES on each worker before pushing any data. In the case of this test, while I did notice that nvidia-smi showed the workers spanning the two devices in my system, all of the cudf chunks in the dask Dataframe were still pinned to the device 0, even though the chunks were spread across both workers.

I do have a notebook where I've successfully been able to pin cudfs to specific devices, following one-process-per-GPU, but this required that I assign each GPU a device id and, in all follow-on processing of the underlying cudfs, I used Numba's `select_device` to always force the device before doing any manipulation on the cudfs. 

Since a cuda context is thread-local, it's possible that the selected device can drift when run on a cluster with multiple threads. Using the technique outlined in the previous paragraph, I was able to allow multi-threaded Dask workers and still guarantee OPG. This does not hold for multi-process workers, however.

I have posted this issue in the dask-cudf project because the dask-cudf is responsible for distributing the cudfs onto the workers and it is in this layer that the workers should be forced to use only the device they've been assigned. I understand CUDA_VISIBLE_DEVICES will default to using the first assigned device id when memory is allocated, however, this does not seem to be strong enough of a constraint to enforce that the cudfs on that worker only ever contain memory allocated from that device.

It's also important that we are not limited to only being able to allocate from that (for instance, by setting CUDA_VISIBLE_DEVICES to a single device) because there are times when we will need to pass around IPC handles and collect pointers from different devices onto a single worker. 

I can certainly supply the exact notebook I used for testing, if that helps.

**Comment by cjnolet** [comment]
I want to follow up with the example I described of how I forced OPG within dask-cuml:

First, I assigned a GPU to each worker:
```
def assign_gpus():
    client = default_client()

    """
    Supports a multi-GPU & multi-Node environment by assigning a single local GPU
    to each worker in the cluster. This is necessary due to Numba's restriction
    that only a single CUDA context (and thus a single device) can be active on a 
    thread at a time. 

    The GPU assignments are valid as long as the future returned from this function
    is held in scope. This allows any functions that need to allocate GPU data to
    utilize the CUDA context on the same device, otherwise data could be lost.
    """

    workers = list(client.has_what().keys())
    hosts_dict = build_host_dict(workers)

    print(str(hosts_dict))

    def get_gpu_info():
        import numba.cuda
        return [x.id for x in numba.cuda.gpus]

    gpu_info = dict([(host, client.submit(get_gpu_info,
                                          workers=[(host, random.sample(hosts_dict[host], 1)[0])]))
                     for host in hosts_dict])
    wait(list(gpu_info.values()))

    # Scatter out a GPU device ID to workers
    f = []
    for host, future in gpu_info.items():
        gpu_ids = future.result()
        ports = random.sample(hosts_dict[host], min(len(gpu_ids), len(hosts_dict[host])))

        f.extend([client.scatter(device_id, workers=[(host, port)]) for device_id, port in zip(gpu_ids, ports)])

    wait(f)

    return f, workers

assignments = assign_gpus()
```
Next, since I controlled how the underlying cudfs were distributed, I was able to have each worker create a cudf with mocked data for testing:
```
def create_cudf(dev):
    import numba.cuda
    import numpy as np
    numba.cuda.select_device(dev)
    logging.debug("Creating dataframe on device " + str(dev))
    return (dev, cudf.DataFrame(
        [('a', np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0]).astype(np.float32)), 
         ('b', np.array([2.0, 3.0, 4.0, 5.0, 6.0, 7.0]).astype(np.float32))]
    ))

res = [client.submit(create_cudf, future, workers = [worker]) for future, worker in zip(assignments, workers)]
wait(res)
```

So now that I have a future holding both the data and the device assignments on each worker, I am able to have each follow-on function executed on the workers make a call to `numba.cuda.select_device()` to force the memory to stay pinned to the assigned device. For instance, when I'm gathering IPC handles:

```
def get_ipc_handles(data):
    dev, gpu_matrix = data
    # Select the device BEFORE doing any processing of the cudf to avoid possible peer copy in case current thread defaulted to a different device.
    select_device(dev)

    in_handle = gpu_matrix.get_ipc_handle()
    return (dev, in_handle)
```

**Comment by cjnolet** [comment]
After looking through the cudf code a bit, I notice that the there is a serialization layer in there that appears to be smart enough to use IPC Handles when passing cudfs from one process to another on the same host. Is it a safe assumption that the dask layer must be using this serialization logic when cudfs are moved across workers? 

I also see that the cudf serializer is using the same cuda context on both the source and on the destination.

I believe the problem here is related strictly to the use-case where a user starts with a single cudf and calls `dask-cudf.from_cudf()` to create their dask-dataframe. It would be nice if we could set an environment variable on the workers to allow peer copies when the cudf reaches the destination worker and a different device was selected than the one at the source. 

How does this sound?

**Comment by mrocklin** [comment]
We'll be redoing all of the serialization work here pretty shortly.  I
wouldn't suggest building on top of it.  I can appreciate that that's
probably not a particularly satisfying answer.  My apologies.
