### ISSUE TITLE
dask_cudf.from_cudf fails for single row dataframes

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#80]
Repro:
```
>>> import cudf, dask_cudf
>>> x = cudf.DataFrame({'a': [1]})
>>> x
<cudf.DataFrame ncols=1 nrows=1 >
>>> y = dask_cudf.from_cudf(x, npartitions=1)
>>> y
<dask_cudf.DataFrame | 0 tasks | 0 npartitions>
```

**Comment by mrocklin** [comment]
We should probably just remove that function.  I recommend `dask.dataframe.from_pandas` instead.  

Thanks for raising this issue.  I'll clean things up shortly to prevent future confusion.

**Comment by trstovall** [comment]
Here I am just creating a literal (and arbitrary) `cudf.DataFrame` to reproduce the bug.  The intended use is to recover a `dask_cudf.DataFrame` from mapped `dask_cudf.DataFrame.partitions`.  That mapping may reduce a partition to fewer than two rows.  In such a case, would `dask.dataframe.from_pandas` provide that functionality without the partitions needing to be translated to `pandas.DataFrame`?

**Comment by mrocklin** [comment]
Yes, `dd.from_pandas` can produce a dask dataframe of cudf dataframes without moving to Pandas

```python
In [1]: import cudf, dask_cudf

In [2]: x = cudf.DataFrame({'a': [1]})

In [3]: y = dask_cudf.from_cudf(x, npartitions=1)

In [4]: y
Out[4]: <dask_cudf.DataFrame | 1 tasks | 1 npartitions>

In [5]: y.compute()
Out[5]: <cudf.DataFrame ncols=1 nrows=1 >

In [6]: y.map_partitions(type).compute()
Out[6]:
0    <class 'cudf.dataframe.dataframe.DataFrame'>
dtype: object
```

This is part of the effort laid out [here](http://blog.dask.org/2019/01/13/dask-cudf-first-steps) which attempts to remove dask-cudf functionality, and just make the somewhat more mature dask.dataframe codebase comfortable handling Pandas-like dataframes.

I'm not entirely certain that I answered your question above.  If something is still missing please speak up.

**Comment by trstovall** [comment]
Yes, that answers the question.  However, your code snippet correctly computes a `dask_cudf.DataFrame` object from a `cudf.DataFrame` with a single row using `dask_cudf.from_cudf`.  I will pull and build dask and dask-cudf master branches and verify the same on my end.

**Comment by mrocklin** [comment]
Ah, indeed.  I meant to use `dd.from_pandas`.  I think that I'm operating on a local branch where I've set `from_cudf = dd.from_pandas`.  My apologies for the confusion.

**Comment by mrocklin** [comment]
This has been fixed.  We've removed the `dask_cudf.from_cudf` implementation in favor of `dd.from_pandas.
