### ISSUE TITLE
max operation changes data in dataframe

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/dask-cudf#87]
I am trying to find out the max value in a column in the dask-cudf dataframe. Currently using the max operation alters the data in the dataframe which I observe by printing data in each rank. The following code reproduces the issue.

**CODE** :
```
import dask.dataframe as dd
import dask_cudf
from toolz import first, assoc
import cudf
from collections import defaultdict
from dask.distributed import Client, wait, default_client, futures_of
client = Client(scheduler_file = "/home/iroy/cluster.json", direct_to_workers = True)

def print_data_and_rank(data):
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    print(data)

def parse_host_port(address):
    if '://' in address:
        address = address.rsplit('://', 1)[1]
    host, port = address.split(':')
    port = int(port)
    return host, port

def max_operation(ddf):
    client = default_client()
    if isinstance(ddf, dd.DataFrame):
        # THE MAX OPERATION THAT CAUSES ISSUE
        max_node_src_col = ddf[ddf.columns[0]].max()
        parts = ddf.to_delayed()
        parts = client.compute(parts)
        wait(parts)
    key_to_part_dict = dict([(str(part.key), part) for part in parts])
    who_has = client.who_has(parts)
    worker_map = []
    for key, workers in who_has.items():
        print("workers")
        print(workers)
        worker = parse_host_port(first(workers))
        worker_map.append((worker, key_to_part_dict[key]))
    print("Printing data...")
    gpu_futures = [client.submit(print_data_and_rank, part, workers=[worker]) for worker, part in worker_map]


input_df = cudf.DataFrame({'a':[9,9,9,9],'b':[8,8,8,8]})

print(input_df)
ddf = dask_cudf.from_cudf(input_df, chunksize=1).persist()
print("DASK CUDF: ", ddf)

max_operation(ddf)
```

**OUTPUT**(4 partitions, 4 ranks):
        a    b
0      1  255
        a    b
1       1    8
        a    b
2      9    8
        a    b
3      9    8

**Comment by mrocklin** [comment]
And, just to be clear, you don't want to just call `df.column_name.max().compute()` here, correct?

> Currently using the max operation alters the data in the dataframe which I observe by printing data in each rank

>         max_node_src_col = ddf[ddf.columns[0]].max()

So, it looks like this code never actually gets computed.  Recall that dask dataframe is lazy by default, so, on its own, this line doesn't do anything.  I would be surprised if it had an effect.

**Comment by Iroy30** [comment]
If I understand your question correctly, yes, I initially calculated it as max_node_src_col = ddf[ddf.columns[0]].max().compute(). That gave me the same error. So I removed compute just to narrow it down to the max operation.

**Comment by mrocklin** [comment]
Just to be clear, dask's max computation seems to work ok for me.

```python
In [1]: import cudf

In [2]: df = cudf.DataFrame({'x': [1, 2, 3, 4, 5, 4, 3, 2, 1]})

In [3]: import dask.dataframe as dd

In [4]: ddf = dd.from_pandas(df, npartitions=4)

In [5]: ddf.x.max().compute()
Out[5]: 5
```

It sounds like you're saying that the max operation is modifying the data somehow, without calling compute.  This would be very surprising.  If this is the case my guess is that it has more to do with cudf than with the MPI machinery you have in your example.  Are you able to reproduce this issue without the MPI machinery, or is it necessary to reproduce the problem?

**Comment by Iroy30** [comment]
yes the max works properly, however it messes with the data. It's not an MPI issue, I have used it just to print out data in each rank.

**Comment by mrocklin** [comment]
The only reason I can imagine for modifying data would be something odd happening within cudf's operations.   Unfortunately none of those devs are likely to be familiar with the Dask+MPI trick that we're using here.  If it's possible to remove that trick but still demonstrate a problem then that would be useful.  Generally the fewer technological systems we can engage the more and more people we'll be able to include in helping to track this down.  For example, if you can even reproduce this without Dask and just with cudf then we can upstream it to those devs.

If you're able to reproduce this issue without MPI that would be helpful.

**Comment by mrocklin** [comment]
Here is an example showing the same state of the dataframes using an in-process cluster.  Unfortunately I'm unable to reproduce the issue.

```python
from dask.distributed import LocalCluster
cluster = LocalCluster(processes=False, n_workers=2, threads_per_worker=1)

import cudf
df = cudf.DataFrame({'a':[9,9,9,9],'b':[8,8,8,8]})

import dask.dataframe as dd
from dask.distributed import Client
client = Client(cluster)

ddf = dd.from_pandas(df, npartitions=4).persist()

a, b = cluster.workers

dict(a.data)
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 0)": <cudf.DataFrame ncols=2 nrows=1 >,
#  "('from_pandas-692826b2e338cf1e81545e5431788655', 2)": <cudf.DataFrame ncols=2 nrows=2 >}

dict(b.data)
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 1)": <cudf.DataFrame ncols=2 nrows=1 >}

{k: v.to_pandas() for k, v in a.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 0)":    b  a
#  0  8  9, "('from_pandas-692826b2e338cf1e81545e5431788655', 2)":    b  a
#  2  8  9
#  3  8  9}

{k: v.to_pandas() for k, v in b.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 1)":    b  a
#  1  8  9}

ddf.a.max().compute()
# 9

# {k: v.to_pandas() for k, v in a.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 0)":    b  a
#  0  8  9, "('from_pandas-692826b2e338cf1e81545e5431788655', 2)":    b  a
#  2  8  9
#  3  8  9}

{k: v.to_pandas() for k, v in b.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 1)":    b  a
#  1  8  9}
```

**Comment by Iroy30** [comment]
When I try to run the same code with few minor changes. (ex: desk_cudf.from_cudf instead of dd.from_pandas) I get the following error.

```
from dask.distributed import LocalCluster
cluster = LocalCluster(processes=False, n_workers=2, threads_per_worker=1)
import dask_cudf
import cudf
df = cudf.DataFrame({'a':[9,9,9,9],'b':[8,8,8,8]})

import dask.dataframe as dd
from dask.distributed import Client
client = Client(cluster)

ddf = dask_cudf.from_cudf(df, npartitions=4).persist()

a, b = cluster.workers

dict(a.data)
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 0)": <cudf.DataFrame ncols=2 nrows=1 >,
#  "('from_pandas-692826b2e338cf1e81545e5431788655', 2)": <cudf.DataFrame ncols=2 nrows=2 >}

dict(b.data)
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 1)": <cudf.DataFrame ncols=2 nrows=1 >}

{k: v.to_pandas() for k, v in a.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 0)":    b  a
#  0  8  9, "('from_pandas-692826b2e338cf1e81545e5431788655', 2)":    b  a
#  2  8  9
#  3  8  9}

{k: v.to_pandas() for k, v in b.data.items()}
# {"('from_pandas-692826b2e338cf1e81545e5431788655', 1)":    b  a
#  1  8  9}

ddf.a.max().compute()
# 9

print(dict(a.data))
#Traceback (most recent call last):
#File "test_temp.py", line 22, in <module>
#    print({k: v.to_pandas() for k, v in a.data.items()})
#File "test_temp.py", line 22, in <dictcomp>
#    print({k: v.to_pandas() for k, v in a.data.items()})
#RuntimeError: dictionary changed size during iteration
```

**Comment by Iroy30** [comment]
In my initial code, computing the max after computing the parts solves the unintended data modification problem. Closing the issue.
